import BaseInfoAnalysis
age=BaseInfoAnalysis.get_age()
sex=BaseInfoAnalysis.get_sex()
city=BaseInfoAnalysis.get_city()
brand_model=BaseInfoAnalysis.get_brand_model()
list_date=BaseInfoAnalysis.get_listing_date()
list_price=BaseInfoAnalysis.get_listing_price()
location=BaseInfoAnalysis.get_location()
print(age)
print(sex)
print(city)
print(brand_model)
print(location)
print(list_date)
print(list_price)
